<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="N4.aspx.cs" Inherits="N4" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head2" Runat="Server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="headline" Runat="Server">
</asp:Content>
<asp:Content ID="Content5" ContentPlaceHolderID="Main" Runat="Server">
    <h1 style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: 59px / 59px ReformaNarrowMedium; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        8 זני חיות מרהיבים שנכחדו השנה</h1>
    <h2 style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: 27px ReformaNarrowRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        עד מתי 2021: השנה נכחדו כמה זנים נפלאים של חיות, שלעולם לא נזכה עוד לראות בטבע. 
        תשכחו מהשפן עם הנקודה, מעכשיו תראו רק שפן בלי נקודה. פרידה מהזנים האציליים 
        והמרהיבים שנעלמו מחיינו לעד</h2>
    <h4 style="box-sizing: border-box; margin: 28px 0px 0px; padding: 0px; border: 0px; font: 25px ReformaNarrowMedium; vertical-align: baseline; color: rgb(0, 0, 0); clear: both; letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        1. שפן עם נקודה</h4>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        השפן עם הנקודה נראה בדיוק כמו שפן רגיל, אולם על גופו יש נקודה. השנה נכחד יצור 
        פלאי זה, ומעכשיו לא נראה עוד בטבע שפנים עם הנקודה, רק בלי נקודה. איזו טרגדיה.</p>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <img alt="" height="370" src="https://img.mako.co.il/2020/11/12/SHAF1.jpg" 
            style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; display: block;" 
            width="555" /></p>
    <h4 style="box-sizing: border-box; margin: 28px 0px 0px; padding: 0px; border: 0px; font: 25px ReformaNarrowMedium; vertical-align: baseline; color: rgb(0, 0, 0); clear: both; letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        2. זברה דקת פס</h4>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        לזן היפיפה הזה של זברות יש פסים דקים יותר מבדרך כלל. במשך שנים הלכו הזברות דקות 
        הפס והתמעטו, ועכשיו כנראה ניאלץ להסתפק בזברות עם פסים עבים בלבד. לא ברור איך 
        ייראו חיינו מעתה והלאה.</p>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <img alt="" height="363" src="https://img.mako.co.il/2020/11/12/ZEBRA.jpg" 
            style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; display: block;" 
            width="555" /></p>
    <h4 style="box-sizing: border-box; margin: 28px 0px 0px; padding: 0px; border: 0px; font: 25px ReformaNarrowMedium; vertical-align: baseline; color: rgb(0, 0, 0); clear: both; letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        3. תנין עם צ&#39;ופצ&#39;יק</h4>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        אין ספק שהאבידה הגדולה מכולן היא היעלמותו של התנין עם הצ&#39;ופצ&#39;יק, תנין שתכונתו 
        הייחודית והמופלאה היא שיש לו על הראש צ&#39;ופצ&#39;יק. כנראה שהצ&#39;ופצ&#39;יק לא התאים לסביבתו 
        הטבעית וגרם למותו של הזן התניני הזה, ואנו אבלים על כך.</p>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <img alt="" height="370" src="https://img.mako.co.il/2020/11/12/CROC.jpg" 
            style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; display: block;" 
            width="555" /></p>
    <h4 style="box-sizing: border-box; margin: 28px 0px 0px; padding: 0px; border: 0px; font: 25px ReformaNarrowMedium; vertical-align: baseline; color: rgb(0, 0, 0); clear: both; letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        4. פיל הסלעים</h4>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        בניגוד לפיל רגיל שעומד על האדמה, פיל הסלעים מעדיף לעמוד על סלעים. בטבע תוכלו 
        למצוא אותו עומד על סלעים או מתכוון לעמוד על סלעים. פיל הסלעים האחרון נפטר בחודש 
        האחרון, וצאצאינו יזכו לראות רק פילים על האדמה, ולידם סלעים ריקים בלי אף פיל.</p>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <img alt="" height="396" src="https://img.mako.co.il/2020/11/12/ELEP.jpg" 
            style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; display: block;" 
            width="555" /></p>
    <h4 style="box-sizing: border-box; margin: 28px 0px 0px; padding: 0px; border: 0px; font: 25px ReformaNarrowMedium; vertical-align: baseline; color: rgb(0, 0, 0); clear: both; letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        5. דביבון צחור-טחול</h4>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        במבט ראשון הדביבון צחור-הטחול נראה כמו דביבונים אחרים, אולם מבפנים הוא שונה 
        לגמרי - הטחול שלו בצבע לבן. גם חיה מופלאה זו בדרך להכחדה - ובקרוב נראה רק 
        דביבונים עם טחול בצבע רגיל. למה, אלוהים???</p>
    <figure class="w634x388 id161c61569b93a410VgnVCM2000002a0c10acRCRD" style="box-sizing: border-box; margin: 26px -82px 26px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; display: block; width: 634px; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <img alt="דביבון ליד מים (צילום: ויקיפדיה)" height="388" loading="lazy" 
        src="https://img.mako.co.il/2014/12/11/Procyon_lotor_i.jpg" 
        style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; display: block;" 
        title="דביבון ליד מים (צילום: ויקיפדיה)" width="634" /><figcaption class="credit" style="box-sizing: border-box; margin: 10px 0px 0px; padding: 0px; border: 0px; font: 10px OpenSansHebrewBold; vertical-align: baseline; display: block; color: rgb(147, 164, 176);"><span 
        style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">דביבון 
    צחור-טחול<span>&nbsp;</span>|<span>&nbsp;</span>צילום: ויקיפדיה</span></figcaption></figure><h4 
        style="box-sizing: border-box; margin: 28px 0px 0px; padding: 0px; border: 0px; font: 25px ReformaNarrowMedium; vertical-align: baseline; color: rgb(0, 0, 0); clear: both; letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        6. טיגריס פוקסייה אף</h4>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        לרוב הטיגריסים יש אף ורדרד, אולם לטיגריס פוקסייה-האף יש אף בגוון טיפה יותר 
        פוקסייה. מדענים לא בטוחים אם אכן מדובר בזן נפרד או פשוט בטיגריסים רגילים עם אף 
        ורדורד שעומדים בצל, אבל בכל מקרה כבר לא רואים בסביבה את הטיגריס הזה בשנים 
        האחרונות וגם זו טרגדיה נוראית.</p>
    <figure class="w634x388 id243354857b144610VgnVCM2000002a0c10acRCRD" style="box-sizing: border-box; margin: 26px -82px 26px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; display: block; width: 634px; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <img alt="טיגריס (צילום: אינסטגרם/eko.julianto)" height="388" loading="lazy" 
        src="https://img.mako.co.il/2018/06/27/aarty_i.jpg" 
        style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; display: block;" 
        title="טיגריס (צילום: אינסטגרם/eko.julianto)" width="634" /><figcaption class="credit" style="box-sizing: border-box; margin: 10px 0px 0px; padding: 0px; border: 0px; font: 10px OpenSansHebrewBold; vertical-align: baseline; display: block; color: rgb(147, 164, 176);"><span 
        style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">טיגריס 
    פוקסייה-אף<span>&nbsp;</span>|<span>&nbsp;</span>צילום: אינסטגרם/eko.julianto</span></figcaption></figure><h4 
        style="box-sizing: border-box; margin: 28px 0px 0px; padding: 0px; border: 0px; font: 25px ReformaNarrowMedium; vertical-align: baseline; color: rgb(0, 0, 0); clear: both; letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        7. נחש טיפה יותר ארוך מבדרך כלל</h4>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        נחש התירס בדרך כלל מגיע לאורך של עד 182 סנטימטר, אולם 
        הנחש-הטיפה-יותר-ארוך-מבדרך-כלל מגיע לאורך של 184.493 סנטימטר. מה יהיה עכשיו 
        כשהוא נכחד? נשארנו עם סתם נחשים מבאסים של 182 סנטימטר. ארור תהיה, סבא-מוות!</p>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <img caption="false" height="374" 
            src="https://img.mako.co.il/2020/11/12/shutterstock_113663551.jpg" 
            style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; display: block;" 
            width="555" /></p>
    <h4 style="box-sizing: border-box; margin: 28px 0px 0px; padding: 0px; border: 0px; font: 25px ReformaNarrowMedium; vertical-align: baseline; color: rgb(0, 0, 0); clear: both; letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        8. שפן עם שתי נקודות</h4>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        דומה מאוד לשפן עם הנקודה, רק שלשפן הזה יש עוד נקודה. פלא הבריאה, והוא נלקח 
        מאיתנו! טבע, אנחנו מתחננים לסליחתך. איננו ראויים לך עוד.</p>
</asp:Content>

