<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="N6.aspx.cs" Inherits="N6" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head2" Runat="Server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="headline" Runat="Server">
</asp:Content>
<asp:Content ID="Content5" ContentPlaceHolderID="Main" Runat="Server">
    <h1 style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: 59px / 59px ReformaNarrowMedium; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        הדברים שעשו לנו את ה-5,780 שנה</h1>
    <h2 style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: 27px ReformaNarrowRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        עץ, קרנף והצורה משולש: לרגל ראש השנה וסגירת 5,780 שנה לקיום העולם, קבלו סיכום 
        מדליק של כל מה שאהבנו (וגם קצת פחות) ב-5,780 שנה האלה</h2>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        &nbsp;</p>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
         ואו,&nbsp;5,780 שנה. מי היה מאמין שזה עבר כל כך מהר? רגע אחד העולם נברא, וכבר אנחנו 
        מסכמים אותו. ואלה היו חתיכת&nbsp;5,780 שנה: מלחמות, אסונות, היווצרויות של הרים, 
        התפתחויות טכנולוגיות, ג&#39;וקים ואפילו המצאת הפירה. הספק לא רע ליקום אחד קטן!</span></p>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
        אז הגיע הזמן להכתיר את הכוכבים הבולטים של ה-5,780 שנה שחלפו, ולצורך כך התכנסנו 
        כל מערכת Wako כדי להצביע ולהשפיע. היו הרבה ויכוחים, אבל בסוף הצלחנו להרכיב רשימה 
        מייצגת של כל מה שאהבנו ושנאנו ב-5,780 השנה האלה. אז בואו נתחיל!</span></p>
    <h4 style="box-sizing: border-box; margin: 28px 0px 0px; padding: 0px; border: 0px; font: 25px ReformaNarrowMedium; vertical-align: baseline; color: rgb(0, 0, 0); clear: both; letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
        הצמח הכי פופולרי:&nbsp;עץ</span></h4>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        אין ספק שעץ הוא אחד האלמנטים הפופולריים ביותר בעולם הצומח. אנחנו אוהבים להישען 
        עליו בפיקניקים, לשתול אותו בט&quot;ו בשבט, למחות כשכורתים אותו ואפילו<span>&nbsp;</span><a 
            href="https://www.youtube.com/watch?v=k0YU4pAYR7I" 
            style="box-sizing: border-box; margin: 0px; padding: 0px; border-width: 0px 0px 2px; border-top-style: initial; border-right-style: initial; border-bottom-style: solid; border-left-style: initial; border-top-color: initial; border-right-color: initial; border-bottom-color: rgba(0, 174, 239, 0.5); border-left-color: initial; border-image: initial; font: inherit; vertical-align: baseline; text-decoration: none; color: inherit; background-image: linear-gradient(120deg, rgba(0, 174, 239, 0.5) 0%, rgba(0, 174, 239, 0.5) 100%); background-repeat: no-repeat; background-size: 100% 0em; background-position: 0px 100%; transition: background-size 0.125s ease-in 0s;">לכתוב 
        עליו שירים</a>. עץ, המשך בדרך זו!</p>
    <figure class="w634x388 id8e17a46bf45d9510VgnVCM2000002a0c10acRCRD" style="box-sizing: border-box; margin: 26px -82px 26px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; display: block; width: 634px; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <img alt="ברוש מצוי באילניה (צילום: חנן ישכר, קרן קיימת לישראל)" height="388" 
        loading="lazy" src="https://img.mako.co.il/2017/01/25/IldTREess_5_i.jpg" 
        style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; display: block;" 
        title="ברוש מצוי באילניה (צילום: חנן ישכר, קרן קיימת לישראל)" width="634" /><figcaption class="credit" style="box-sizing: border-box; margin: 10px 0px 0px; padding: 0px; border: 0px; font: 10px OpenSansHebrewBold; vertical-align: baseline; display: block; color: rgb(147, 164, 176);"><span 
        style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">עץ. 
    אהבנו!<span>&nbsp;</span>|<span>&nbsp;</span>צילום: חנן ישכר, קרן קיימת לישראל</span></figcaption></figure><h4 
        style="box-sizing: border-box; margin: 28px 0px 0px; padding: 0px; border: 0px; font: 25px ReformaNarrowMedium; vertical-align: baseline; color: rgb(0, 0, 0); clear: both; letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
        גרם השמיים האהוב: שמש</span></h4>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        במירוץ צמוד עם הירח, שהגיע למקום השני בדירוג, קטפה השמש את תואר &quot;גרם השמיים 
        האהוב עלינו&quot;. ומה הפלא? היא חמה, עגולה, צהובה, עושה פוטוסינתזה - כל מה שאפשר 
        לבקש מגרם שמיים. זו בהחלט הייתה ה-5,780 שנה של השמש. כבוד!</p>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        &nbsp;</p>
    <figure class="w634x388 id80278a31ef8fe410VgnVCM100000290c10acRCRD" style="box-sizing: border-box; margin: 26px -82px 26px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; display: block; width: 634px; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <img alt="פברואר היה חם מהרגיל - המומחים מזהירים (צילום: חדשות 2)" height="388" 
        loading="lazy" src="https://img.mako.co.il/2016/03/14/663959_I.jpg" 
        style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; display: block;" 
        title="פברואר היה חם מהרגיל - המומחים מזהירים (צילום: חדשות 2)" width="634" /><figcaption class="credit" style="box-sizing: border-box; margin: 10px 0px 0px; padding: 0px; border: 0px; font: 10px OpenSansHebrewBold; vertical-align: baseline; display: block; color: rgb(147, 164, 176);"><span 
        style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">שמש. 
    שיחקת אותה!<span>&nbsp;</span>|<span>&nbsp;</span>צילום: חדשות 2</span></figcaption></figure><p 
        style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    </p>
    <h4 style="box-sizing: border-box; margin: 28px 0px 0px; padding: 0px; border: 0px; font: 25px ReformaNarrowMedium; vertical-align: baseline; color: rgb(0, 0, 0); clear: both; letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
        הצורה הכי מגניבה: משולש</span></h4>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        &nbsp;מה עוד אפשר לומר על צורה שיש לה פאקינג שלוש צלעות? תראו לנו עוד צורה שמסוגלת 
        לעשות את זה חוץ מהמשולש. כמה פשוט, ככה אלגנטי, ובאופן בלתי מתלהם או ראוותני 
        שמצליח לשלב העצמה והכלה עם רוגע והקשבה, ולהשיב את הכוונות למקור בשמחה ובאחריות.&nbsp;</p>
    <figure class="w634x388 id79f1abea15f34710VgnVCM200000650a10acRCRD" style="box-sizing: border-box; margin: 26px -82px 26px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; display: block; width: 634px; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <img alt="משולש (איור: רחלי רוטנר)" height="388" loading="lazy" 
        src="https://img.mako.co.il/2020/08/30/TRIANGLE_i.jpg" 
        style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; display: block;" 
        title="משולש (איור: רחלי רוטנר)" width="634" /><figcaption class="credit" style="box-sizing: border-box; margin: 10px 0px 0px; padding: 0px; border: 0px; font: 10px OpenSansHebrewBold; vertical-align: baseline; display: block; color: rgb(147, 164, 176);"><span 
        style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">משולש. 
    איזו עוצמה!<span>&nbsp;</span>|<span>&nbsp;</span>איור: רחלי רוטנר</span></figcaption></figure><h4 
        style="box-sizing: border-box; margin: 28px 0px 0px; padding: 0px; border: 0px; font: 25px ReformaNarrowMedium; vertical-align: baseline; color: rgb(0, 0, 0); clear: both; letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        &nbsp;החיה הכי מיותרת: קרנף</h4>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">
        כאילו, בוא. אתה גדול ואפור ויש לך קרן מעל הפה, בשביל מה? מה הפואנטה? לא התרשמנו, 
        בלשון המעטה. Thumbs Down!</span></p>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        &nbsp;</p>
    <figure class="w634x388 ida186c74948eaa510VgnVCM100000290c10acRCRD" style="box-sizing: border-box; margin: 26px -82px 26px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; display: block; width: 634px; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <img alt="טיבור הקרנף בספארי (צילום: טיבור יגר)" height="388" loading="lazy" 
        src="https://img.mako.co.il/2017/03/08/854665_I.jpg" 
        style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; display: block;" 
        title="טיבור הקרנף בספארי (צילום: טיבור יגר)" width="634" /><figcaption class="credit" style="box-sizing: border-box; margin: 10px 0px 0px; padding: 0px; border: 0px; font: 10px OpenSansHebrewBold; vertical-align: baseline; display: block; color: rgb(147, 164, 176);"><span 
        style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">קרנף. 
    נסה שוב בפעם הבאה<span>&nbsp;</span>|<span>&nbsp;</span>צילום: טיבור יגר</span></figcaption></figure><p 
        style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    </p>
    <h4 style="box-sizing: border-box; margin: 28px 0px 0px; padding: 0px; border: 0px; font: 25px ReformaNarrowMedium; vertical-align: baseline; color: rgb(0, 0, 0); clear: both; letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
        הכי מחמם את האוכל מהר:&nbsp;מיקרוגל</span></h4>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
        ניסינו את האש, ניסינו את התנור וניסינו את הכיריים, אבל לאורך כל 5,780 השנה הדבר 
        שחימם את האוכל שלנו הכי מהר זה מיקרוגל. סורי, שני ענפים שמתחככים זה בזה ממש מהר!</span></p>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        &nbsp;</p>
    <figure class="w634x388 idf51fcce0644e2510VgnVCM2000002a0c10acRCRD" style="box-sizing: border-box; margin: 26px -82px 26px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; display: block; width: 634px; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <img alt="מיקרוגל (צילום: Shutterstock)" height="388" loading="lazy" 
        src="https://img.mako.co.il/2016/02/15/miCRoGAloauiJWAVE_09_i.jpg" 
        style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; display: block;" 
        title="מיקרוגל (צילום: Shutterstock)" width="634" /><figcaption class="credit" style="box-sizing: border-box; margin: 10px 0px 0px; padding: 0px; border: 0px; font: 10px OpenSansHebrewBold; vertical-align: baseline; display: block; color: rgb(147, 164, 176);"><span 
        style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">מיקרוגל. 
    אספלט לוהט? פחות<span>&nbsp;</span>|<span>&nbsp;</span>צילום: Shutterstock</span></figcaption></figure><p 
        style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    </p>
    <h4 style="box-sizing: border-box; margin: 28px 0px 0px; padding: 0px; border: 0px; font: 25px ReformaNarrowMedium; vertical-align: baseline; color: rgb(0, 0, 0); clear: both; letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        המספר הכי מוזר: 111</h4>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        אתה מספר או שלושה מקלות? ג&#39;יזס, תחליט כבר. אין לתאר.</p>
    <h4 style="box-sizing: border-box; margin: 28px 0px 0px; padding: 0px; border: 0px; font: 25px ReformaNarrowMedium; vertical-align: baseline; color: rgb(0, 0, 0); clear: both; letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        ההמצאה הכי יעילה: רצפה</h4>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        מה היינו עושים בלי רצפה? כנראה נופלים לתוך ליבת כדור הארץ. הרצפה - או הקרקע, למי 
        שמעדיף להתייחס אליה ככה - משמשת לנו כאמצעי לדרוך עליו וחוצצת בינינו לבין החלל 
        הריק שמתחתינו, ובכך מונעת את נפילתנו הנצחית אל תוך תהומות האדמה. אין לנו מושג מי 
        הגאון שהמציא אותה, אבל זה בהחלט בא לנו בול בזמן!</p>
    <figure class="w634x388 iddb3ccfef73ebb510VgnVCM2000002a0c10acRCRD" style="box-sizing: border-box; margin: 26px -82px 26px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; display: block; width: 634px; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <img alt="כפות רגליים גבר (צילום: LeventeGyori, Shutterstock)" height="388" 
        loading="lazy" 
        src="https://img.mako.co.il/2017/04/30/shutterstock_405968515_i.jpg" 
        style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; display: block;" 
        title="כפות רגליים גבר (צילום: LeventeGyori, Shutterstock)" width="634" 
        dir="rtl" /><figcaption class="credit" style="box-sizing: border-box; margin: 10px 0px 0px; padding: 0px; border: 0px; font: 10px OpenSansHebrewBold; vertical-align: baseline; display: block; color: rgb(147, 164, 176);"><span 
        style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">רגליים 
    על רצפה. איפה הן היו היום בלעדיה?<span>&nbsp;</span>|<span>&nbsp;</span>צילום: 
    LeventeGyori, Shutterstock</span></figcaption></figure><h4 
        style="box-sizing: border-box; margin: 28px 0px 0px; padding: 0px; border: 0px; font: 25px ReformaNarrowMedium; vertical-align: baseline; color: rgb(0, 0, 0); clear: both; letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">
        הרגע הכי מפתיע:&nbsp;הצליבה של ישו בשנת 33 לספירה</span></h4>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">
        פייר, לא ראינו את זה בא. היה נדמה לרגע שהרומאים הם צ&#39;יל איתו והכול, ואז פוף, 
        צליבה, נצרות וכל זה. מי היה מאמין?</span></p>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        &nbsp;</p>
    <figure class="w634x388 idf802f4c92172d510VgnVCM2000002a0c10acRCRD" style="box-sizing: border-box; margin: 26px -82px 26px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; display: block; width: 634px; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <img alt="צליבת ישו (צילום: ויקיפדיה)" height="388" loading="lazy" 
        src="https://img.mako.co.il/2017/07/09/TZLIVA_i.jpg" 
        style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; display: block;" 
        title="צליבת ישו (צילום: ויקיפדיה)" width="634" dir="rtl" /><figcaption class="credit" style="box-sizing: border-box; margin: 10px 0px 0px; padding: 0px; border: 0px; font: 10px OpenSansHebrewBold; vertical-align: baseline; display: block; color: rgb(147, 164, 176);"><span 
        style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">הצליבה 
    של ישו. סירייסלי?<span>&nbsp;</span>|<span>&nbsp;</span>צילום: ויקיפדיה</span></figcaption></figure><p 
        style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    </p>
    <h4 style="box-sizing: border-box; margin: 28px 0px 0px; padding: 0px; border: 0px; font: 25px ReformaNarrowMedium; vertical-align: baseline; color: rgb(0, 0, 0); clear: both; letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
        התכונה הכימית הכי מבטיחה: מסיסות</span></h4>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        &nbsp;פירוק לחלקיקים במגע עם חומר אחר מאץ&#39;? בהתחלה היינו סקפטיים, אבל מאז שפרצה 
        התכונה הכימית מסיסות לחיינו, כבר אי אפשר להסתכל על חומרים באותו האופן. אנחנו 
        מהמרים שהתכונה הכימית מסיסות עוד תפתיע ותהפוך לחלק בלתי נפרד מחיינו גם ב-5,780 
        שנה הבאות. מסיס זה הכי, אחי!</p>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        &nbsp;</p>
    <figure class="w634x388 id5e0499e82d96c410VgnVCM2000002a0c10acRCRD" style="box-sizing: border-box; margin: 26px -82px 26px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; display: block; width: 634px; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <img alt="מלח (צילום: rsester, Thinkstock)" height="388" loading="lazy" 
        src="https://img.mako.co.il/2019/10/17/asass_i.jpg" 
        style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; display: block;" 
        title="מלח (צילום: rsester, Thinkstock)" width="634" /><figcaption class="credit" style="box-sizing: border-box; margin: 10px 0px 0px; padding: 0px; border: 0px; font: 10px OpenSansHebrewBold; vertical-align: baseline; display: block; color: rgb(147, 164, 176);"><span 
        style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">אתה 
    מסיס אחי? ברוב הנוזלים ברור!<span>&nbsp;</span>|<span>&nbsp;</span>צילום: rsester, 
    Thinkstock</span></figcaption></figure><p 
        style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    </p>
    <h4 style="box-sizing: border-box; margin: 28px 0px 0px; padding: 0px; border: 0px; font: 25px ReformaNarrowMedium; vertical-align: baseline; color: rgb(0, 0, 0); clear: both; letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
        הכי WTF:&nbsp;הקונספט של הזמן&nbsp;</span></h4>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        &nbsp;זה דבר יחסי? זה ממד נוסף? אפשר לנסוע בו? ואם כן - מה קורה כשאנחנו הורגים את סבא 
        שלנו בעבר? אין ספק שקונספט הזמן הוא אחד הדברים הכי לא מובנים בכל הקטע הזה שנקרא 
        יקום, ואולי כדאי שירגיע עם כל הקריזות ויתנהג נורמלי. מיצינו קשות, כפרה.</p>
    <figure class="w634x388 id272f7f3520fb9610VgnVCM2000002a0c10acRCRD" style="box-sizing: border-box; margin: 26px -82px 26px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; display: block; width: 634px; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <img alt="שעון קיץ (צילום: BrAt82, ShutterStock)" height="388" loading="lazy" 
        src="https://img.mako.co.il/2019/03/27/14e4536f-005b-4df1-9419-6294236504e6_i.jpg" 
        style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; display: block;" 
        title="שעון קיץ (צילום: BrAt82, ShutterStock)" width="634" /><figcaption class="credit" style="box-sizing: border-box; margin: 10px 0px 0px; padding: 0px; border: 0px; font: 10px OpenSansHebrewBold; vertical-align: baseline; display: block; color: rgb(147, 164, 176);"><span 
        style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">שעון. 
    עכשיו אתה גם מודד את עצמך עם שני מקלות זזים?! התחרפנת?!<span>&nbsp;</span>|<span>&nbsp;</span>צילום: 
    BrAt82, ShutterStock</span></figcaption></figure><h4 
        style="box-sizing: border-box; margin: 28px 0px 0px; padding: 0px; border: 0px; font: 25px ReformaNarrowMedium; vertical-align: baseline; color: rgb(0, 0, 0); clear: both; letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
        הכי פחות אהבנו:&nbsp;מוות בעינויים</span></h4>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
        חברי המערכת אמנם טרם ניסו את זה על עצמם, אבל אין ספק שאם תשאלו את רוב האנשים מה 
        הם הכי פחות ישמחו לקבל, הרי שזה מוות בעינויים. ייתכן שזה השילוב של מוות עם 
        עינויים שגורם לנו להירתע מהקונספט - גם למות באמצע החיים, וגם לעבור עינויים תוך 
        כדי? No thanks! - אבל די ברור שעדיף לכולנו בלי. נקסט, מה שנקרא.&nbsp;</span></p>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        &nbsp;</p>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: OpenSansHebrewBold; vertical-align: baseline;">
        ומה אתם הכי אהבתם ב-5,780 השנה האחרונות? ספרו לנו בתגובות!</strong></p>
</asp:Content>

