<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="N9.aspx.cs" Inherits="Default3" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head2" Runat="Server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="headline" Runat="Server">
</asp:Content>
<asp:Content ID="Content5" ContentPlaceHolderID="Main" Runat="Server">
    <h1 style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: 59px / 59px ReformaNarrowMedium; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        המדריך של שרה נתניהו לדברים קלים ופשוטים</h1>
    <h2 style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: 27px ReformaNarrowRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        אחרי המתכון של שרה נתניהו לעוגת ביסקוויטים קלה ופשוטה (רק חצי שעה לגירור 
        שוקולד!), הנה עוד כמה טיפים של הגברת הראשונה לפעולות קלות ופשוטות</h2>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        &nbsp;</p>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <a href="https://www.instagram.com/tv/B_kT_pWpDxY/?utm_source=ig_web_copy_link" 
            rel="noopener" 
            style="box-sizing: border-box; margin: 0px; padding: 0px; border-width: 0px 0px 2px; border-top-style: initial; border-right-style: initial; border-bottom-style: solid; border-left-style: initial; border-top-color: initial; border-right-color: initial; border-bottom-color: rgba(0, 174, 239, 0.5); border-left-color: initial; border-image: initial; font: inherit; vertical-align: baseline; text-decoration: none; color: inherit; background-image: linear-gradient(120deg, rgba(0, 174, 239, 0.5) 0%, rgba(0, 174, 239, 0.5) 100%); background-repeat: no-repeat; background-size: 100% 0em; background-position: 0px 100%; transition: background-size 0.125s ease-in 0s;" 
            target="_blank">המתכון הקל והפשוט של שרה לעוגת ביסקוויטים</a></p>
    <h4 style="box-sizing: border-box; margin: 28px 0px 0px; padding: 0px; border: 0px; font: 25px ReformaNarrowMedium; vertical-align: baseline; color: rgb(0, 0, 0); clear: both; letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
        <img alt="" height="362" src="https://img.mako.co.il/2020/04/30/SARA1.jpg" 
            style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; display: block;" 
            width="520" /></span></h4>
    <h4 style="box-sizing: border-box; margin: 28px 0px 0px; padding: 0px; border: 0px; font: 25px ReformaNarrowMedium; vertical-align: baseline; color: rgb(0, 0, 0); clear: both; letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
        איך לשטוף את הרצפה בקלות ובפשטות</span></h4>
    <ol style="box-sizing: border-box; margin: 26px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; list-style: none; counter-reset: li 0; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <li style="box-sizing: border-box; margin: 0px 0px 6px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            פנו את הרצפה מכל החפצים והרהיטים והוציאו אותם לגינה (אם אין גינה, ניתן לשכור 
            מחסן ולהוביל לשם את הרהיטים לאחסון עד סוף הספונג&#39;ה).</span></li>
        <li style="box-sizing: border-box; margin: 0px 0px 6px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            עיקרו ממקומן את כל הבלטות באמצעות כפית. אם אתם מתקשים לעקור אותן עם כפית, השתמשו 
            בכף. זה עלול לקחת זמן מה - אל תתייאשו!</span></li>
        <li style="box-sizing: border-box; margin: 0px 0px 6px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            סדרו את הבלטות בשורה ושטפו כל אחת בנפרד.</span></li>
        <li style="box-sizing: border-box; margin: 0px 0px 6px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            יבשו כל בלטה באמצעות הבל הפה שלכם.</span></li>
        <li style="box-sizing: border-box; margin: 0px 0px 6px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            החזירו את הבלטות למקומן.</span></li>
    </ol>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
        פשוט וקל!</span></p>
    <aside class="share-bar not-for-print" style="box-sizing: border-box; margin: 0px -82px 0px 0px; padding: 0px 2px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; display: block; width: 56px; position: absolute; height: 170px; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <div class="fonts" 
        style="box-sizing: border-box; margin: 0px; padding: 0px 0px 4px; border-width: 0px 0px 3px; border-top-style: initial; border-right-style: initial; border-bottom-style: solid; border-left-style: initial; border-top-color: initial; border-right-color: initial; border-bottom-color: rgb(209, 216, 220); border-left-color: initial; border-image: initial; font: inherit; vertical-align: baseline; text-align: center; width: 60px; position: relative;">
        <a class="plus" 
            href="https://www.mako.co.il/culture-wako/Article-9bc1b90314ac171027.htm?sCh=69f3269cbe9f4610&amp;pId=25483675#" 
            style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 27px; font-family: inherit; vertical-align: baseline; text-decoration: none; width: 27px; height: 27px; display: inline-block;">
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="20" height="16" viewBox="0 0 20 16">
        <defs>
        <path id="plus" d="M19.198 3.77c-.042 1.092-.186 1.88-.432 2.362-.194.39-.66.918-1.396 1.587L16.1 8.887l3.479 6.195c.228.398.152.597-.229.597h-2.107c-.44 0-.753-.182-.94-.546l-4.05-7.694-.57.42c-.432.313-.648 1.049-.648 2.208v5.04c0 .381-.14.572-.42.572H8.738c-.347 0-.52-.2-.52-.597v-5.04c0-1.794.626-3.182 1.878-4.164l.724-.571L8.089.546C7.896.182 8.019 0 8.459 0h2.158c.33 0 .563.14.698.419l3.377 6.348.762-.711c.482-.457.74-1.063.774-1.816L16.38.47c0-.313.165-.47.495-.47h1.98c.296 0 .445.19.445.571l-.102 3.2zM1.818 9.022H.198c-.132 0-.198-.063-.198-.19v-.855c0-.133.066-.199.198-.199h1.62V6.198c0-.132.066-.198.199-.198h.854c.132 0 .198.066.198.198v1.58h1.634c.132 0 .198.065.198.198v.854c0 .128-.066.191-.198.191H3.07v1.655c0 .132-.066.198-.198.198h-.854c-.133 0-.199-.066-.199-.198V9.02z">
        </path>
        </defs>
        <g fill="none" fill-rule="evenodd">
        <mask id="plus-m" fill="#fff">
        <use xlink:href="#plus">
        <path id="plus0" 
            d="M19.198 3.77c-.042 1.092-.186 1.88-.432 2.362-.194.39-.66.918-1.396 1.587L16.1 8.887l3.479 6.195c.228.398.152.597-.229.597h-2.107c-.44 0-.753-.182-.94-.546l-4.05-7.694-.57.42c-.432.313-.648 1.049-.648 2.208v5.04c0 .381-.14.572-.42.572H8.738c-.347 0-.52-.2-.52-.597v-5.04c0-1.794.626-3.182 1.878-4.164l.724-.571L8.089.546C7.896.182 8.019 0 8.459 0h2.158c.33 0 .563.14.698.419l3.377 6.348.762-.711c.482-.457.74-1.063.774-1.816L16.38.47c0-.313.165-.47.495-.47h1.98c.296 0 .445.19.445.571l-.102 3.2zM1.818 9.022H.198c-.132 0-.198-.063-.198-.19v-.855c0-.133.066-.199.198-.199h1.62V6.198c0-.132.066-.198.199-.198h.854c.132 0 .198.066.198.198v1.58h1.634c.132 0 .198.065.198.198v.854c0 .128-.066.191-.198.191H3.07v1.655c0 .132-.066.198-.198.198h-.854c-.133 0-.199-.066-.199-.198V9.02z">
        </path>
        </use>
        </mask>
        <use fill="#000" xlink:href="#plus">
        <path id="plus1" 
            d="M19.198 3.77c-.042 1.092-.186 1.88-.432 2.362-.194.39-.66.918-1.396 1.587L16.1 8.887l3.479 6.195c.228.398.152.597-.229.597h-2.107c-.44 0-.753-.182-.94-.546l-4.05-7.694-.57.42c-.432.313-.648 1.049-.648 2.208v5.04c0 .381-.14.572-.42.572H8.738c-.347 0-.52-.2-.52-.597v-5.04c0-1.794.626-3.182 1.878-4.164l.724-.571L8.089.546C7.896.182 8.019 0 8.459 0h2.158c.33 0 .563.14.698.419l3.377 6.348.762-.711c.482-.457.74-1.063.774-1.816L16.38.47c0-.313.165-.47.495-.47h1.98c.296 0 .445.19.445.571l-.102 3.2zM1.818 9.022H.198c-.132 0-.198-.063-.198-.19v-.855c0-.133.066-.199.198-.199h1.62V6.198c0-.132.066-.198.199-.198h.854c.132 0 .198.066.198.198v1.58h1.634c.132 0 .198.065.198.198v.854c0 .128-.066.191-.198.191H3.07v1.655c0 .132-.066.198-.198.198h-.854c-.133 0-.199-.066-.199-.198V9.02z">
        </path>
        </use>
        <g fill="#000" mask="url(#plus-m)">
        <path d="M-60-86H88V62H-60z">
        </path>
        </g>
        </g>
        </svg>
        </a><span>&nbsp;</span><a class="minus" 
            href="https://www.mako.co.il/culture-wako/Article-9bc1b90314ac171027.htm?sCh=69f3269cbe9f4610&amp;pId=25483675#" 
            style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 27px; font-family: inherit; vertical-align: baseline; text-decoration: none; width: 27px; height: 27px; display: inline-block;"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="17" height="12" viewBox="0 0 17 12"><defs><path id="minus" d="M15.752 2.756c-.03.756-.13 1.3-.299 1.635-.135.27-.457.635-.967 1.098l-.879.809 2.409 4.289c.158.275.105.413-.159.413h-1.459c-.304 0-.521-.126-.65-.378l-2.804-5.326-.395.29c-.3.217-.449.726-.449 1.53v3.488c0 .264-.096.396-.29.396h-1.3c-.24 0-.36-.138-.36-.413v-3.49c0-1.242.433-2.202 1.3-2.882l.501-.396L8.061.523c-.134-.252-.05-.377.255-.377H9.81c.229 0 .39.096.484.29l2.338 4.394.527-.492c.334-.317.513-.735.536-1.257l.106-2.61c0-.217.114-.325.342-.325h1.372c.205 0 .307.131.307.395l-.07 2.215zM4.824 3.805c.128 0 .192.066.192.198v.923c0 .132-.064.198-.192.198H.456c-.132 0-.198-.066-.198-.198v-.923c0-.132.066-.198.198-.198h4.368z"></path></defs><g fill="none" fill-rule="evenodd"><mask id="minus-m" fill="#fff"><use xlink:href="#minus"><path 
            id="minus0" 
            d="M15.752 2.756c-.03.756-.13 1.3-.299 1.635-.135.27-.457.635-.967 1.098l-.879.809 2.409 4.289c.158.275.105.413-.159.413h-1.459c-.304 0-.521-.126-.65-.378l-2.804-5.326-.395.29c-.3.217-.449.726-.449 1.53v3.488c0 .264-.096.396-.29.396h-1.3c-.24 0-.36-.138-.36-.413v-3.49c0-1.242.433-2.202 1.3-2.882l.501-.396L8.061.523c-.134-.252-.05-.377.255-.377H9.81c.229 0 .39.096.484.29l2.338 4.394.527-.492c.334-.317.513-.735.536-1.257l.106-2.61c0-.217.114-.325.342-.325h1.372c.205 0 .307.131.307.395l-.07 2.215zM4.824 3.805c.128 0 .192.066.192.198v.923c0 .132-.064.198-.192.198H.456c-.132 0-.198-.066-.198-.198v-.923c0-.132.066-.198.198-.198h4.368z"></path></use></mask><use fill="#000" xlink:href="#minus"><path 
            id="minus1" 
            d="M15.752 2.756c-.03.756-.13 1.3-.299 1.635-.135.27-.457.635-.967 1.098l-.879.809 2.409 4.289c.158.275.105.413-.159.413h-1.459c-.304 0-.521-.126-.65-.378l-2.804-5.326-.395.29c-.3.217-.449.726-.449 1.53v3.488c0 .264-.096.396-.29.396h-1.3c-.24 0-.36-.138-.36-.413v-3.49c0-1.242.433-2.202 1.3-2.882l.501-.396L8.061.523c-.134-.252-.05-.377.255-.377H9.81c.229 0 .39.096.484.29l2.338 4.394.527-.492c.334-.317.513-.735.536-1.257l.106-2.61c0-.217.114-.325.342-.325h1.372c.205 0 .307.131.307.395l-.07 2.215zM4.824 3.805c.128 0 .192.066.192.198v.923c0 .132-.064.198-.192.198H.456c-.132 0-.198-.066-.198-.198v-.923c0-.132.066-.198.198-.198h4.368z"></path></use><g fill="#000" mask="url(#minus-m)"><path d="M-86-87H62V61H-86z"></path></g></g></svg></a></div>
    </aside>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        &nbsp;<img alt="" height="362" src="https://img.mako.co.il/2020/04/30/SARA3.jpg" 
            style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; display: block;" 
            width="520" /></p>
    <h4 style="box-sizing: border-box; margin: 28px 0px 0px; padding: 0px; border: 0px; font: 25px ReformaNarrowMedium; vertical-align: baseline; color: rgb(0, 0, 0); clear: both; letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
        איך לקלף תפוז בקלות ובפשטות</span></h4>
    <ol style="box-sizing: border-box; margin: 26px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; list-style: none; counter-reset: li 0; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <li style="box-sizing: border-box; margin: 0px 0px 6px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            <p style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">
                <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
                חרצו את קליפת התפוז לארבעה חלקים באמצעות סכין.</span></p>
        </li>
        <li style="box-sizing: border-box; margin: 0px 0px 6px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            <p style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">
                <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
                קשרו בחוט כל חלק של הקליפה לכלי רכב כבד כגון ג&#39;יפ, משאית וכו&#39;.</span></p>
        </li>
        <li style="box-sizing: border-box; margin: 0px 0px 6px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            <p style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">
                <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
                החזיקו בתפוז בחוזקה ובקשו מארבעת הנהגים בכלי הרכב לנסוע קדימה בכל המהירות, עד 
                שקטע הקליפה הקשור לרכבם יתנתק מהפרי.</span></p>
        </li>
        <li style="box-sizing: border-box; margin: 0px 0px 6px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            <p style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">
                <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
                אכלו את התפוז לתיאבון.</span></p>
        </li>
        <li style="box-sizing: border-box; margin: 0px 0px 6px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            <p style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">
                <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
                הודיעו לנהגים באמצעות טלפון סלולרי שהם יכולים לחזור.</span></p>
        </li>
    </ol>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
        פשוט וקל!</span></p>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        &nbsp;<img alt="" height="362" src="https://img.mako.co.il/2020/04/30/SARA4.jpg" 
            style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; display: block;" 
            width="520" /></p>
    <h4 style="box-sizing: border-box; margin: 28px 0px 0px; padding: 0px; border: 0px; font: 25px ReformaNarrowMedium; vertical-align: baseline; color: rgb(0, 0, 0); clear: both; letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
        איך ללבוש חולצה בקלות ובפשטות</span></h4>
    <ol style="box-sizing: border-box; margin: 26px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; list-style: none; counter-reset: li 0; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <li style="box-sizing: border-box; margin: 0px 0px 6px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            מתחו והרחיבו את החולצה עד אשר תהיה לפחות בגודל כפול מגופכם.</span></li>
        <li style="box-sizing: border-box; margin: 0px 0px 6px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            העיפו את החולצה באוויר ועמדו בדיוק מתחתיה.</span></li>
        <li style="box-sizing: border-box; margin: 0px 0px 6px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            קפצו לתוך החולצה באופן כזה שתיפול דרך ראשכם וסביב גופכם.</span></li>
        <li style="box-sizing: border-box; margin: 0px 0px 6px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            באמצעות ערכת תפירה פשוטה, הצרו בחזרה את החולצה כך ששוב תתאים למידותיכם.</span></li>
    </ol>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
        פשוט וקל!</span></p>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        &nbsp;</p>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        &nbsp;<img alt="" height="362" src="https://img.mako.co.il/2020/04/30/SARA2.jpg" 
            style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; display: block;" 
            width="520" /></p>
    <h4 style="box-sizing: border-box; margin: 28px 0px 0px; padding: 0px; border: 0px; font: 25px ReformaNarrowMedium; vertical-align: baseline; color: rgb(0, 0, 0); clear: both; letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
        איך להחליף מצעים בקלות ובפשטות</span></h4>
    <ol style="box-sizing: border-box; margin: 26px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; list-style: none; counter-reset: li 0; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <li style="box-sizing: border-box; margin: 0px 0px 6px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            שכבו על גבכם מתחת למיטה.</span></li>
        <li style="box-sizing: border-box; margin: 0px 0px 6px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            באמצעות מסורית פשוטה, נסרו חור בינוני בלוח העץ של המיטה, עד שתגיעו למזרן.</span></li>
        <li style="box-sizing: border-box; margin: 0px 0px 6px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            החדירו קשית שתייה לתוך המזרן.</span></li>
        <li style="box-sizing: border-box; margin: 0px 0px 6px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            כשאתם עדיין שוכבים על גבכם מתחת למיטה, שאבו בפיכם דרך הקשית פירורי בד מהמזרן. 
            תוכלו לירוק אותם לתוך קערה שהכנתם מראש.</span></li>
        <li style="box-sizing: border-box; margin: 0px 0px 6px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            באופן זה, רוקנו לחלוטין את כל המזרן מהמילוי שלו, פירור אחר פירור, עד שיישאר ממנו 
            רק הסדין שעוטף אותו.</span></li>
        <li style="box-sizing: border-box; margin: 0px 0px 6px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            סלקו את הסדין והניחו במקומו סדין חדש.</span></li>
        <li style="box-sizing: border-box; margin: 0px 0px 6px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            באמצעות קשית השתייה, החזירו פירור-אחר-פירור דרך החור עד שהמזרן יווצר מחדש, הפעם 
            מתחת לסדין נקי.</span></li>
    </ol>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
        פשוט וקל!</span></p>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        &nbsp;<img alt="" height="362" src="https://img.mako.co.il/2020/04/30/SARA5.jpg" 
            style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; display: block;" 
            width="520" /></p>
    <h4 style="box-sizing: border-box; margin: 28px 0px 0px; padding: 0px; border: 0px; font: 25px ReformaNarrowMedium; vertical-align: baseline; color: rgb(0, 0, 0); clear: both; letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
        איך להחליף נורה בקלות ובפשטות</span></h4>
    <ol style="box-sizing: border-box; margin: 26px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; list-style: none; counter-reset: li 0; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <li style="box-sizing: border-box; margin: 0px 0px 6px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            רכשו קוף מאולף מסוג מקוק.</span></li>
        <li style="box-sizing: border-box; margin: 0px 0px 6px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            אלפו אותו במשך חודשים לרקוד באופן מושלם.</span></li>
        <li style="box-sizing: border-box; margin: 0px 0px 6px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            שלחו אותו לתחרות ריקודים, שבה יזכה במקום הראשון.</span></li>
        <li style="box-sizing: border-box; margin: 0px 0px 6px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            המתינו שיגיע לביתכם שליח מיוחד להעניק לכם את הפרס.</span></li>
        <li style="box-sizing: border-box; margin: 0px 0px 6px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
            בקשו מהשליח שאם הוא כבר כאן שיחליף לכם נורה.</span></li>
    </ol>
    <p style="box-sizing: border-box; margin: 10px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: OpenSansHebrewRegular; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
        פשוט וקל!</span></p>
</asp:Content>

